function plot_airfoil_data(X1, Y1, X2, Y2, X3, Y3, X4, Y4)
%PLOT_AIRFOIL_DATA(X1,Y1,X2,Y2,X3,Y3,X4,Y4)
%  X1:  vector of x data Re 3x10^6
%  Y1:  vector of y data Re 3x10^6
%  X2:  vector of x data Re 6x10^6
%  Y2:  vector of y data Re 6x10^6
%  X3:  vector of x data Re 9x10^6
%  Y3:  vector of y data Re 9x10^6
%  X4:  vector of x data Rugocidad Estandar
%  Y4:  vector of y data Rugocidad Estandar

%  Auto-generated by MATLAB on 22-Jul-2012 22:52:01

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YMinorGrid','on','YGrid','on','XMinorGrid','on','XGrid','on');
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',2,'DisplayName','Re 3x10^6');

% Create plot
plot(X2,Y2,'Parent',axes1,'LineWidth',2,'DisplayName','Re 6x10^6');

% Create plot
plot(X3,Y3,'Parent',axes1,'LineWidth',2,'DisplayName','Re 9x10^6');

% Create plot
plot(X4,Y4,'Parent',axes1,'LineWidth',2,...
    'DisplayName',['Rugocidad',sprintf('\n'),'Estandar']);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','EastOutside');

